### PR TITLE
State knowledge

### PR DESCRIPTION
**Pull request by leohtkam**
When the user returns to a finished survey page, the text should be different to reflect this.

### CODE REVIEW

**Comment by impguard** [comment]
What do people think about this. I had a more global state management in mind, but thinking about it, there should be no reason not to localize it to surveyQuestionsController as done here. It just means any additional state knowledge will essentially be "hardcoded" in a sense to this controller. Opinions?

**Comment by leohtkam** [comment]
Global state makes more sense and somewhat cleaner. I added a pivotal task that I will work on next iteration, to switch to using a global state.

**Comment by impguard** [comment]
+1

**Comment by whsieh** [comment]
+1

**Pull request closed without merging**
