### PR TITLE
License

### PR DESCRIPTION
**Pull request by nickfong**
Add GNU GPLv3 to repo

### CODE REVIEW

**Comment by whsieh** [comment]
+1.

**Comment by leohtkam** [comment]
I am fine with whatever license but the professor recommends the MIT license. Does using that makes a difference?

**Comment by nickfong** [comment]
See the group chat (from yesterday) for my explanation. Also:

> Also see http://choosealicense.com/licenses/#gpl-v3 if you're not familiar with GPL3 vs MIT

**Comment by smartfuse** [comment]
+1

**Comment by nickfong** [comment]
Regarding @smartfuse's question about a non-commercial license, see the OSI docs [1]; forcing non-commercial use doesn't conform to the guidelines of an open source project.  Also, AFAIK, software is generally discouraged from being licensed under something like CC.  

Since GPL is a copyleft license (unlike say the MIT license), all derivative works must be licensed under GPL and all derivative source must also be disclosed.  I went with GPL for this reason.  Plus, Linux and Git are licensed under GPL, so if it's good enough for Linus Torvalds' projects, it's good enough for me :)

[1] http://opensource.org/docs/osd

**Comment by kuu2** [comment]
+1

**Pull request merged**
