### PR TITLE
Added cucumber for homepage newsfeed.

### PR DESCRIPTION
**Pull request by whsieh**
Cucumber tests for the newsfeed in the homepage.
Super basic, but necessary. Should not affect any other features.

### CODE REVIEW

**Comment by leohtkam** [comment]
+1

**Comment by impguard** [comment]
+0.981

**Comment by whsieh** [comment]
+0.018

**Comment by leohtkam** [comment]
Need 0.001 to merge

**Comment by nickfong** [comment]
+0.0005

**Comment by smartfuse** [comment]
+1

**Pull request merged**
